In [22]:
def unique(li):
    u=[]
    for i in li:
        if i not in u:
            u.append(i)
    print(u)
li=[1,2,3,4,5,23,56,89]
unique(li)
def SumofTwo(li):
    sum=0
    c=0
    for i in li:
        if i not in li:
            if len(li)==2:
                sum=sum+int(i)
                c=c+1
                avg=sum/c
                
    print(sum)
SumofTwo(li)
    


[1, 2, 3, 4, 5, 23, 56, 89]
0


In [26]:
def Average(li):
    
    unique = []
    c,sum =0,0
    for i in li:
        if i not in unique:
            unique.append(i)
    l=list(filter(lambda i: len(i)==3,unique))
    for i in l:
        sum+=int(i)
        c+=1
    print(sum//c)
li=input().split()
Average(li)


56 37 100 200 4 6 7 8 34 57 
150


In [27]:
def Division(li):
    unique=[]
    for i in range(len(li)-1):
        for j in range(i+1,len(li)):
            d=abs(int(li[i])-int(li[j]))
            if d not in unique:
                unique.append(d)
    print(min(unique))
t=int(input())
for i in range(1,t+1):
    li=input().split()
    Division(li)

3
6 3 4 5
1
4 7 9 1 
2
100 3 6 108
3


In [36]:
def urls(li):
    t=int(input())
    unique =[]
    u1 =[]
    for i in range(t):
        li=input()
        unique.append(li)
    for i in unique:
         if i not in u1:
            u1.append(i)
    print(len(u1))
    for i in u1:
        print(i,end='\n')
urls(li)

5
www.google.com
www.hackerearth.com
www.hackerearth.com
www.hackerearth.com
www.yahoo.com
3
www.google.com
www.hackerearth.com
www.yahoo.com


In [39]:


keyfile='DataFiles/key.txt'
def dictionaryKeyFile(keyfile):
    key={}
    with open(keyfile,'r') as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key


def encryptMarksData(datafile,keyfile):
    #CONSTRUCT A DICTIONARY FOR KEY DATA
    key=dictionaryKeyFile(keyfile)
    with open(datafile,'r') as f:
        filedata=f.read().split('\n')
    with open('DataFiles/encryptMarksData.txt','w') as f:
        for mark in filedata:
            line=' '
            for n in mark:
                line+=key[n]
            f.write(line+'\n')
    return
datafile='DataFiles/marks1.txt'
encryptMarksData(datafile,keyfile)
                
        
    

In [41]:
keyfile='DataFiles/key.txt'
key=dictionaryKeyFile(keyfile)

evenkeys={item for item in key.items() if int(item[0])%2==0}
evenkeys

{('0', '4'), ('2', '6'), ('4', '8'), ('6', '0'), ('8', '2')}

In [43]:
keyfile='DataFiles/key.txt'
key=dictionaryKeyFile(keyfile)

evenkeys={item for item in key}
evenkeys

{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

In [ ]:
# Numpy Library

    * processing N-Dimensional Arrays

In [5]:
import numpy as np

li=[1,2,3]

a=np.array(li)
a

b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
rn=np.random.randint(0,100,size=10)
rn

array([40, 14,  4, 20, 44, 17, 69, 61, 73, 98])

In [8]:
m3=np.random.randint(0,2,size=(3,3,3))
m3

array([[[0, 0, 0],
        [1, 0, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 1, 1],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [1, 0, 0]]])

In [9]:
m3=np.random.randint(0,2,size=(3,3,3))
m3[2][2][2][1]

IndexError: invalid index to scalar variable.

In [10]:
rn.ndim

1

In [11]:
rn.shape

(10,)

In [12]:
rn.size

10

In [13]:
m3.size

27

In [14]:
m3.dtype

dtype('int32')

In [15]:
m3.itemsize

4

In [16]:
m3.nbytes

108

In [17]:
m3[4:7]

array([], shape=(0, 3, 3), dtype=int32)

In [18]:
print(m3)

[[[0 1 0]
  [1 0 1]
  [0 1 0]]

 [[0 1 0]
  [0 0 0]
  [1 0 0]]

 [[1 1 0]
  [1 0 1]
  [0 0 0]]]


In [27]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [29]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
b.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# PANDAS


USE CASES
    * Data Cleaning
    * Data Transformation
    * Data Analysis
 
 
 Notations
     * series
     * DataFrames
     

In [44]:
import pandas as pd


internal1={'s1':21,'s2':18,'s3':67 }

internal1=pd.Series(internal1)

internal2={'s1':51,'s2':78,'s3':63 }
internal2=pd.Series(internal2)
internal2

s1    51
s2    78
s3    63
dtype: int64

In [48]:
final={'Internal1':internal1, 'Internal2': internal2}
final=pd.DataFrame(final)
final

Internal1  Internal2
s1         21         51
s2         18         78
s3         67         63

In [50]:
final.columns


Index(['Internal1', 'Internal2'], dtype='object')

In [51]:
final.values    ##Lists of all rows

array([[21, 51],
       [18, 78],
       [67, 63]], dtype=int64)

In [52]:
final.values[2]

array([67, 63], dtype=int64)

In [53]:
final.values[2,0]

67

In [56]:
for row in final.values:
    print('Internal1-',row[0],'Internal2-',row[1])

Internal1- 21 Internal2- 51
Internal1- 18 Internal2- 78
Internal1- 67 Internal2- 63


In [57]:
final.loc[3]=[15,18]
final

Internal1  Internal2
s1         21         51
s2         18         78
s3         67         63
3          15         18

In [58]:
final.drop(3)

Internal1  Internal2
s1         21         51
s2         18         78
s3         67         63